In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [3]:
raw_data=np.genfromtxt("C:\\Users\\R S SUNEEL KRISHNA\Downloads\\loan-data.csv",delimiter=";",skip_header=1,autostrip=True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
np.isnan(raw_data).sum()

88005

In [5]:
temp=np.nanmax(raw_data).round(2)+1
temp_mean=np.nanmean(raw_data,axis=0)

C:\Users\R S SUNEEL KRISHNA\AppData\Local\Temp\ipykernel_29120\2810383542.py:2: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(raw_data,axis=0)


In [6]:
temp_stats=np.array([np.nanmin(raw_data,axis=0),
                              temp_mean,
                              np.nanmax(raw_data,axis=0)])
temp_stats

C:\Users\R S SUNEEL KRISHNA\AppData\Local\Temp\ipykernel_29120\2834679002.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats=np.array([np.nanmin(raw_data,axis=0),
C:\Users\R S SUNEEL KRISHNA\AppData\Local\Temp\ipykernel_29120\2834679002.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data,axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# splitting data

In [7]:
columns_strings=np.argwhere(np.isnan(temp_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [8]:
columns_numeric=np.argwhere(np.isnan(temp_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Re-importing dataset

In [9]:
raw_data_strings=np.genfromtxt("C:\\Users\\R S SUNEEL KRISHNA\Downloads\\loan-data.csv",
                               delimiter=";",
                               skip_header=1,
                               autostrip=True,
                              usecols=columns_strings,
                              dtype=str)
raw_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [10]:
raw_data_numeric=np.genfromtxt("C:\\Users\\R S SUNEEL KRISHNA\Downloads\\loan-data.csv",
                               delimiter=";",
                               skip_header=1,
                               autostrip=True,
                              usecols=columns_numeric,
                               filling_values=temp
                              )
raw_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [11]:
raw_data_header=np.genfromtxt("C:\\Users\\R S SUNEEL KRISHNA\Downloads\\loan-data.csv",
                               delimiter=";",
                               skip_footer=raw_data.shape[0],#removes all data except 1st row
                               autostrip=True,
                               dtype=str
                              )
raw_data_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [12]:
header_text,header_num=raw_data_header[columns_strings],raw_data_header[columns_numeric]

In [13]:
header_text

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [14]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# creating checkpoints

In [15]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable=np.load(file_name+".npz")
    return(checkpoint_variable)

In [16]:
checkpoint_test=checkpoint("checkpoint-test",header_text,raw_data_strings)

# manupulating test data

In [17]:
header_text

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
header_text[0]="issue_date"

In [19]:
raw_data_strings


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

# issue date

In [20]:
raw_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [21]:
np.unique(raw_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [22]:
raw_data_strings[:,0]=np.chararray.strip(raw_data_strings[:,0],"-15")
raw_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [23]:
months=np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [24]:
for i in range (13):
    raw_data_strings[:,0]=np.where(raw_data_strings[:,0]==months[i],
                                  i,
                                  raw_data_strings[:,0])

In [25]:
np.unique(raw_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

# loan status

In [26]:
raw_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [27]:
np.unique(raw_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [28]:
status_bad=np.array(['','Charged Off','Default','Late (31-120 days)'])

In [29]:
raw_data_strings[:,1]=np.where(np.isin(raw_data_strings[:,1],status_bad),0,1)
raw_data_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

In [30]:
np.unique(raw_data_strings[:,1])

array(['0', '1'], dtype='<U69')

# term

In [31]:
raw_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [32]:
np.unique(raw_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [33]:
raw_data_strings[:,2]=np.chararray.strip(raw_data_strings[:,2]," months")
raw_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [34]:
header_text[2]="term months"

In [35]:
raw_data_strings[:,2]=np.where(raw_data_strings[:,2]=='',
                              60,
                              raw_data_strings[:,2])
raw_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

# grade and subgrade

In [36]:
raw_data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [37]:
np.unique(raw_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [38]:
raw_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [39]:
np.unique(raw_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [40]:
for i in np.unique(raw_data_strings[:,3])[1:]:
    raw_data_strings[:,4]=np.where((raw_data_strings[:,4]=='')&(raw_data_strings[:,4]==i),
    i+'5',
    raw_data_strings[:,4])

In [41]:
np.unique(raw_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [42]:
for i in np.unique(raw_data_strings[:,3])[1:]:
    raw_data_strings[:,4]=np.where((raw_data_strings[:,4]==''),
    'H1',
    raw_data_strings[:,4])

In [43]:
np.unique(raw_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [44]:
raw_data_strings=np.delete(raw_data_strings,3,axis=1)
raw_data_strings

array([['5', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [45]:
header_text

array(['issue_date', 'loan_status', 'term months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [46]:
raw_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [47]:
header_text=np.delete(header_text,3)

In [48]:
header_text

array(['issue_date', 'loan_status', 'term months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [49]:
keys=list(np.unique(raw_data_strings[:,3]))
values=list(range(1,np.unique(raw_data_strings[:,3]).shape[0]+1))
#shape[0]+1 means till the num of elements in that column here 36
dict_sub_grade=dict(zip(keys,values))

In [50]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [51]:
for i in np.unique(raw_data_strings[:,3]):
    raw_data_strings[:,3]=np.where(raw_data_strings[:,3]==i,
                                  dict_sub_grade[i],
                                 raw_data_strings[:,3] )

In [52]:
np.unique(raw_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

# verification

In [53]:
raw_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [54]:
header_text[4]

'verification_status'

In [55]:
np.unique(raw_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [57]:

raw_data_strings[:,4]=np.where((raw_data_strings[:,4]=='')|(raw_data_strings[:,4]=="Not Verified"),
                              0,
                              1)


In [58]:
raw_data_strings[:,4]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

# url

In [59]:
raw_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [60]:
header_text[5]

'url'

In [61]:
np.chararray.strip(raw_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [62]:
raw_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [63]:
raw_data_strings=np.delete(raw_data_strings,5,axis=1)
header_text=np.delete(header_text,5)

In [64]:
header_text

array(['issue_date', 'loan_status', 'term months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [65]:
raw_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

# State address

In [66]:
header_text

array(['issue_date', 'loan_status', 'term months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [67]:
header_text[5]

'addr_state'

In [68]:
raw_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [69]:
np.unique(raw_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [70]:
header_text[5]="state address"

In [71]:
raw_data_strings[:,5]=np.where(raw_data_strings[:,5]=='',
                              0,
                              raw_data_strings[:,5])
raw_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [72]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [73]:
raw_data_strings[:,5]=np.where(np.isin(raw_data_strings[:,5],states_west),1,raw_data_strings[:,5])
raw_data_strings[:,5]=np.where(np.isin(raw_data_strings[:,5],states_south),2,raw_data_strings[:,5])
raw_data_strings[:,5]=np.where(np.isin(raw_data_strings[:,5],states_midwest),3,raw_data_strings[:,5])
raw_data_strings[:,5]=np.where(np.isin(raw_data_strings[:,5],states_east),4,raw_data_strings[:,5])
  

In [74]:
np.unique(raw_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [75]:
raw_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '1', '3']], dtype='<U69')

In [76]:
raw_data_strings=raw_data_strings.astype(int)

In [77]:
raw_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  1,  3]])

In [78]:
checkpoint_string=checkpoint("Checkpoint-strings",header_text,raw_data_strings)

In [79]:
checkpoint_string["header"]

array(['issue_date', 'loan_status', 'term months', 'sub_grade', 'verification_status',
       'state address'], dtype='<U19')

# manupulating numeric columns

In [80]:
raw_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [81]:
np.isnan(raw_data_numeric).sum()

0

In [82]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [83]:
temp

68616520.0

In [84]:
np.isin(raw_data_numeric[:,0],temp)

array([False, False, False, ..., False, False, False])

In [85]:
np.isin(raw_data_numeric[:,0],temp).sum()

0

In [86]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [87]:
temp_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# funded amount

In [88]:
raw_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [89]:
raw_data_numeric[:,2]=np.where(raw_data_numeric[:,2]==temp,
                              temp_stats[0,columns_numeric[2]],
                              raw_data_numeric[:,2])
raw_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

# loan amt,interest rate,total payment,install rate

In [90]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [91]:
for i in [1,3,4,5]:
    raw_data_numeric[:,i]=np.where(raw_data_numeric[:,i]==temp,
                              temp_stats[2,columns_numeric[i]],
                              raw_data_numeric[:,i])
raw_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

# exchange rate

In [92]:
EUR_USD = np.genfromtxt("C:\\Users\\R S SUNEEL KRISHNA\\Downloads\\S28 - A Loan Data Example with NumPy\\EUR-USD.csv", delimiter=',', autostrip=True,dtype=str)
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [93]:
import numpy as np

EUR_USD = np.genfromtxt(
    "C:\\Users\\R S SUNEEL KRISHNA\\Downloads\\S28 - A Loan Data Example with NumPy\\EUR-USD.csv",
    delimiter=',',
    autostrip=True,
    dtype=float,  # Assuming you want to read numerical values
    skip_header=1,
    usecols=3
)

# Now, round the values to 2 decimal places
EUR_USD = np.round(EUR_USD, 2)

print(EUR_USD)


[1.13 1.12 1.08 1.11 1.1  1.12 1.09 1.13 1.13 1.1  1.06 1.09]


In [94]:
raw_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  1,  3]])

In [95]:
raw_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [96]:
exchange_rate=raw_data_strings[:,0]

for i in range(1,13):
    
    exchange_rate=np.where(exchange_rate==i,
                            EUR_USD[i-1],
                            exchange_rate
                           )
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)
exchange_rate
    

array([1.1 , 1.1 , 1.13, ..., 1.12, 1.11, 1.09])

In [97]:
exchange_rate.shape

(10000,)

In [98]:
raw_data_numeric.shape

(10000, 6)

In [99]:
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [100]:
np.hstack((raw_data_numeric,exchange_rate))

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.1 ],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [101]:
raw_data_numeric=np.hstack((raw_data_numeric,exchange_rate))

In [102]:
header_num=np.concatenate((header_num,np.array(["exchange_rate"])))
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

# converting from USD to EUR

In [103]:
columns_dollar=np.array([1,2,4,5])

In [104]:
raw_data_numeric[:,[columns_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [105]:
raw_data_numeric[:,6]

array([1.1 , 1.1 , 1.13, ..., 1.12, 1.11, 1.09])

In [106]:
  for i in columns_dollar:
        raw_data_numeric=np.hstack((raw_data_numeric,np.reshape(raw_data_numeric[:,i]/raw_data_numeric[:,6],(10000,1))))

In [107]:
raw_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31818.18,     1077.15,     8593.6 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27149.32,      849.38,     4235.02],
       [59432726.  ,    15000.  ,    15000.  , ...,    13274.34,      437.93,     1743.21],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8928.57,     1225.87,     1951.46],
       [46154151.  ,    35000.  ,    10000.  , ...,     9009.01,      319.19,     2882.34],
       [66055249.  ,    10000.  ,    10000.  , ...,     9174.31,      284.38,      276.97]])

# Expanding the header

In [108]:
header_add = np.array([column_name + "_EUR" for column_name in header_num[columns_dollar]])


In [109]:
header_add

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [110]:
header_num=np.concatenate((header_num,header_add))

In [111]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [112]:
header_num[columns_dollar]=np.array([column_name + "_USD" for column_name in header_num[columns_dollar]])

In [113]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [116]:
column_index_order=[0,1,7,2,8,3,4,9,5,10,6]

In [117]:
header_num=header_num[column_index_order]

In [118]:
raw_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31818.18,     1077.15,     8593.6 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27149.32,      849.38,     4235.02],
       [59432726.  ,    15000.  ,    15000.  , ...,    13274.34,      437.93,     1743.21],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8928.57,     1225.87,     1951.46],
       [46154151.  ,    35000.  ,    10000.  , ...,     9009.01,      319.19,     2882.34],
       [66055249.  ,    10000.  ,    10000.  , ...,     9174.31,      284.38,      276.97]])

In [119]:
raw_data_numeric=raw_data_numeric[:,column_index_order]

In [120]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

# interest rate

In [121]:
raw_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [122]:
raw_data_numeric[:,5]=raw_data_numeric[:,5]/100

In [123]:
raw_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

# checkpoint

In [124]:
checkpoint_numeric=checkpoint("Checkpoint-numeric",header_num,raw_data_numeric)

In [125]:
checkpoint_numeric["header"],checkpoint_numeric["data"]

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31818.18, ...,     9452.96,     8593.6 ,        1.1 ],
        [57693261.  ,    30000.  ,    27149.32, ...,     4679.7 ,     4235.02,        1.1 ],
        [59432726.  ,    15000.  ,    13274.34, ...,     1969.83,     1743.21,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8928.57, ...,     2185.64,     1951.46,        1.12],
        [46154151.  ,    35000.  ,    31531.53, ...,     3199.4 ,     2882.34,        1.11],
        [66055249.  ,    10000.  ,     9174.31, ...,      301.9 ,      276.97,        1.09]]))

# creating complete dataset

In [128]:
checkpoint_string['data'].shape

(10000, 6)

In [129]:
checkpoint_numeric['data'].shape

(10000, 11)

In [130]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_string['data']))

In [131]:
loan_data


array([[48010226.  ,    35000.  ,    31818.18, ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27149.32, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13274.34, ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8928.57, ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31531.53, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9174.31, ...,        4.  ,        1.  ,        3.  ]])

In [132]:
np.isnan(loan_data).sum()

0

In [134]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_string['header']))

# sorting the dataset

In [135]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [136]:
loan_data

array([[  373332.  ,     9950.  ,     9045.45, ...,       21.  ,        1.  ,        1.  ],
       [  575239.  ,    12000.  ,    10909.09, ...,       36.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8928.57, ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5137.61, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3669.72, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19816.51, ...,        3.  ,        1.  ,        2.  ]])

In [137]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

# storing the dataset

In [138]:
loan_data = np.vstack((header_full, loan_data))

In [140]:
np.savetxt("loan-data-preprocessed-final.csv", 
           loan_data, 
           fmt = '%s',
           delimiter = ',')